apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: helse-brreg
   namespace: default
   labels:
      team: risk
spec:
   image: {{ image }}
   replicas:
      min: 1
      max: 2
   liveness:
      path: /isalive
   readiness:
      path: /isready
   resources:
      limits:
         cpu: 1000m
         memory: 2048Mi
      requests:
         cpu: 500m
         memory: 512Mi
   webproxy: true
   prometheus:
      enabled: true
      path: /metrics
