apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: helse-brreg
   namespace: risk
   labels:
      team: risk
   annotations:
      nais.io/read-only-file-system: "false"
spec:
   image: {{ image }}
   replicas:
      min: 2
      max: 3
   liveness:
      path: /isalive
   readiness:
      path: /isready
   resources:
      limits:
         cpu: 1000m
         memory: 2048Mi
      requests:
         cpu: 500m
         memory: 512Mi
   env:
      - name: JDK_JAVA_OPTIONS
        value: "-Dhttp.proxyHost=webproxy.nais -Dhttps.proxyHost=webproxy.nais -Dhttp.proxyPort=8088 -Dhttps.proxyPort=8088 -Dhttp.nonProxyHosts=localhost|127.0.0.1|10.254.0.1|*.local|*.adeo.no|*.nav.no|*.aetat.no|*.devillo.no|*.oera.no|*.nais.io|*.aivencloud.com|*.intern.dev.nav.no"
   webproxy: true
   prometheus:
      enabled: true
      path: /metrics
